server:
  port: 9010

order-submission:
  group-id: order-submission-group
  topic-name: order-submission-topic
  topic-name-dlt: order-submission-topic.DLT
  group-id-dlt: order-submission-group-DLT
  num-partitions: 4
  num-replicas: 1
  num-threads: 4
  retry-policy:
    max-attempts: 4
  backoff-policy:
    initial-interval: 2000
    multiplier: 2.0
    max-interval: 60000

kafka:
  bootstrapAddress: localhost:9092